### ISSUE TITLE
InvalidConfigurationException

### ISSUE THREAD

**Issue by AppleSa** [Soldier233/VipSystem#2]
[15:43:08 WARN]: org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xDB9F) special characters are not allowed
in "'string'", position 74
[15:43:08 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
[15:43:08 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184)
[15:43:08 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:152)
[15:43:08 WARN]:        at me.zhanshi123.VipSystem.Main.updateDetect(Main.java:38)
[15:43:08 WARN]:        at me.zhanshi123.VipSystem.Main.access$0(Main.java:30)
[15:43:08 WARN]:        at me.zhanshi123.VipSystem.Main$1.run(Main.java:150)
[15:43:08 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[15:43:08 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:43:08 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:43:08 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:43:08 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:43:08 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:43:08 WARN]: Caused by: unacceptable character '?' (0xDB9F) special characters are not allowed
in "'string'", position 74
[15:43:08 WARN]:        at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67)
[15:43:08 WARN]:        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47)
[15:43:08 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
[15:43:08 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
[15:43:08 WARN]:        ... 11 more
[15:43:08 INFO]: VipSystem >>> ÎÞ·¨»ñÈ¡×îÐÂ°æ±¾£¡

**Comment by Soldier233** [comment]
请检查你的config文件是否存在特殊字符
编码是否正确

**Comment by AppleSa** [comment]
这个是获取云端config时报的错误[链接](https://github.com/Soldier233/VipSystem/blob/master/src/me/zhanshi123/VipSystem/Main.java#L36-L39)

**Comment by Soldier233** [comment]
不好意思没仔细看
这个是更新检查，不影响的
